### PR TITLE
Version 4.18.0

### PR DESCRIPTION
**Pull request by uerceg**
- Added `trackAdRevenue` method to `Adjust` interface to allow tracking of ad revenue. With this release added support for `MoPub` ad revenue tracking.
- Added reading of Facebook anonymous ID if available on iOS platform.

### CODE REVIEW

**Comment by fuckingworld** [comment]
Something go wrong:Adjust.prefab cannot be draged in Unity Scene;

**Comment by uerceg** [comment]
🤔 Which Unity IDE version are you using?

**Comment by fuckingworld** [comment]
2017.1.0f3

**Comment by uerceg** [comment]
@fuckingworld We'll release Unity SDK v4.18.1 in a bit and give that one a shot, hopefully it should work for you as well. Will ping you in here once live.

**Comment by uerceg** [comment]
@fuckingworld Feel free to give this one a shot: https://github.com/adjust/unity_sdk/releases/tag/v4.18.1.

**Pull request merged**
