### PR TITLE
AdWords & post build processing

### PR DESCRIPTION
**Pull request by uerceg**
- Adding support for AdWords campaign tracking.
- Removing Python post build scripts in Unity SDK for Unity IDE 5.x.y.
- Docs update.

### CODE REVIEW

**Comment by uerceg** [comment]
@adjust/integration

**Comment by luckey01** [comment]
@LeJohnDuff we should really co-ordinate this better next time: https://github.com/adjust/unity_sdk/pull/76

**Comment by LeJohnDuff** [comment]
Yeah, for sure...

**Comment by uerceg** [comment]
Will be replaced with new PR for upcoming v4.10.0.

**Pull request closed without merging**
