### PR TITLE
fix compile error on Windows platform

### PR DESCRIPTION
**Pull request by IllusionCui**

### CODE REVIEW

**Comment by nonelse** [comment]
merged with v4.10.1

**Comment by IllusionCui** [comment]
@johnou

**Comment by IllusionCui** [comment]
@johnou

**Comment by IllusionCui** [comment]
@johnou 
UNITY_IOS ：#define directive for compiling/executing code for the iOS platform.
If choose the iOS platform on Windows System, the "UNITY_IOS" is active. But the Windows System does't have xcode.

UNITY_EDITOR_OSX : #define directive for Editor code on Mac OSX.
So, I chose the "UNITY_EDITOR_OSX".

**Pull request merged**
